sonar.projectKey=antoine1838_classroom-sorter
sonar.organization=antoine1838

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

# Rapport de couverture généré par `flutter test --coverage`.
sonar.dart.lcov.reportPaths=coverage/lcov.info
